# SpecBridge CLI library: contracts
# Dot-sourced by scripts/specbridge.ps1. Do not run directly.

function Invoke-ValidateCommand {
  $scripts = Invoke-ValidationProfile -SelectedProfile $Profile
  $results = @()
  $failed = $false

  foreach ($script in $scripts) {
    $result = Invoke-ScriptGate -ScriptPath $script
    $results += $result

    if ($result.exit_code -ne 0) {
      $failed = $true
      break
    }
  }

  Write-CliJson ([ordered]@{
    command = "validate"
    ok = (-not $failed)
    profile = $Profile
    results = $results
  })

  if ($failed) {
    exit 1
  }

  exit 0
}

function Invoke-CreateContractCommand {
  if ([string]::IsNullOrWhiteSpace($TaskId)) {
    Fail "TaskId is required"
  }

  if ([string]::IsNullOrWhiteSpace($Title)) {
    Fail "Title is required"
  }

  if ([string]::IsNullOrWhiteSpace($Goal)) {
    Fail "Goal is required"
  }

  if ([string]::IsNullOrWhiteSpace($RelatedIssue)) {
    Fail "RelatedIssue is required"
  }

  $path = Assert-OutputPath `
    -Path $OutputPath `
    -Pattern "^\.specbridge/contracts/.+\.execution\.md$" `
    -Description "a .specbridge/contracts/*.execution.md contract"

  $contract = @"
# Execution Contract: $Title

## Contract Metadata

- contract_id: $TaskId
- related_issue: $RelatedIssue
- created_by: SpecBridge CLI
- created_at: 2026-05-20
- autonomy_profile: full_autopilot
- risk_level: low
- status: draft

## Goal

$Goal

## Context

Generated by the local SpecBridge CLI from declared command inputs.

## Source References

- README.md
- SPECBRIDGE.md
- AGENTS.md
- .specbridge/policy.yaml

## Autonomy Profile

```text
full_autopilot
```

## Risk Level

```text
low
```

## Allowed Scope

```text
To be filled before execution.
```

## Blocked Scope

```text
.env
.env.*
secrets/**
infra/prod/**
runtime product code unless explicitly authorized
production deployment
billing
authentication security changes
authorization security changes
CI/CD security weakening
```

## Acceptance Criteria

- The contract is completed before execution.
- Required validations are declared before execution.
- Scope remains repository-relative and auditable.

## Required Validations

```powershell
powershell -ExecutionPolicy Bypass -File ./scripts/specbridge-smoke.ps1
```

## Stop Conditions

Stop on policy conflict, missing required context, impossible acceptance criteria, secrets, production configuration, billing, authentication security, authorization security, or CI/CD security weakening.

## Merge Policy

Gate-controlled automatic merge is allowed only after required gates pass.

## Deployment Policy

No deployment is allowed.

## Final Report Requirements

The final report must include summary, changed files, validations, policy result, risk result, unresolved risks, merge status, deployment status, and completion status.

## Completion Rule

This task is complete only when the declared validations pass and the final report records evidence.
"@

  Write-Utf8TextFile -Path $path -Value $contract

  Write-CliJson ([ordered]@{
    command = "create-contract"
    ok = $true
    output_path = $path
  })

  exit 0
}

function Invoke-CreateReportCommand {
  if ([string]::IsNullOrWhiteSpace($Summary)) {
    Fail "Summary is required"
  }

  if ($ChangedFile.Count -le 0) {
    Fail "ChangedFile requires at least one path"
  }

  if ($Validation.Count -le 0) {
    Fail "Validation requires at least one record"
  }

  if ([string]::IsNullOrWhiteSpace($PolicyResult)) {
    Fail "PolicyResult is required"
  }

  if ([string]::IsNullOrWhiteSpace($RiskResult)) {
    Fail "RiskResult is required"
  }

  $path = Assert-OutputPath `
    -Path $OutputPath `
    -Pattern "^\.specbridge/reports/.+\.final-report\.json$" `
    -Description "a .specbridge/reports/*.final-report.json final report"

  $normalizedChangedFiles = @($ChangedFile | ForEach-Object { Normalize-RepoPath -Path $_ -FieldName "ChangedFile" })

  $report = [ordered]@{
    summary = $Summary
    changed_files = @($normalizedChangedFiles)
    validations = @($Validation)
    policy_result = $PolicyResult
    risk_result = $RiskResult
    unresolved_risks = @()
    merge_status = "Not applicable."
    deployment_status = "Not applicable."
    completion_status = $CompletionStatus
  }

  Write-Utf8JsonFile -Path $path -Value $report -Depth 6

  Write-CliJson ([ordered]@{
    command = "create-report"
    ok = $true
    output_path = $path
  })

  exit 0
}

function Invoke-AuditPacketCommand {
  if ([string]::IsNullOrWhiteSpace($TaskId)) {
    Fail "TaskId is required"
  }

  $contract = Normalize-RepoPath -Path $ContractPath -FieldName "ContractPath"
  $report = Normalize-RepoPath -Path $ReportPath -FieldName "ReportPath"
  $outputDir = ".specbridge/audit-packets"

  if (-not [string]::IsNullOrWhiteSpace($OutputDirectory)) {
    $outputDir = Normalize-RepoPath -Path $OutputDirectory -FieldName "OutputDirectory"
  }

  $generatorArgs = @(
    "-NoProfile",
    "-ExecutionPolicy",
    "Bypass",
    "-File",
    "./scripts/generate-audit-packet.ps1",
    "-TaskId",
    $TaskId,
    "-ExecutionContractPath",
    $contract,
    "-FinalReportPath",
    $report,
    "-CiStatus",
    $CiStatus,
    "-OutputDirectory",
    $outputDir
  )

  if (-not [string]::IsNullOrWhiteSpace($OutputFileName)) {
    $generatorArgs += @("-OutputFileName", $OutputFileName)
  }

  & powershell @generatorArgs
  $exitCode = $LASTEXITCODE

  if ($exitCode -ne 0) {
    Fail "audit packet generation failed" $exitCode
  }

  $packetName = $OutputFileName

  if ([string]::IsNullOrWhiteSpace($packetName)) {
    $packetName = "$TaskId.audit-packet.json"
  }

  Write-CliJson ([ordered]@{
    command = "audit-packet"
    ok = $true
    output_path = (Normalize-RepoPath -Path (Join-Path $outputDir $packetName) -FieldName "output_path")
  })

  exit 0
}

function Invoke-DetectConflictsCommand {
  $result = Invoke-ScriptGate -ScriptPath "./scripts/validate-contract-scopes.ps1"

  Write-CliJson ([ordered]@{
    command = "detect-conflicts"
    ok = ($result.exit_code -eq 0)
    result = $result
  })

  exit $result.exit_code
}

function Invoke-DecomposeTaskCommand {
  $input = Normalize-RepoPath -Path $InputPath -FieldName "InputPath"
  $output = Assert-OutputPath `
    -Path $OutputPath `
    -Pattern "^\.specbridge/decompositions/.+\.decomposition\.json$" `
    -Description "a .specbridge/decompositions/*.decomposition.json decomposition"

  if (-not (Test-Path -LiteralPath $input)) {
    Fail "InputPath does not exist: $input"
  }

  try {
    $source = Get-Content -LiteralPath $input -Raw -Encoding UTF8 | ConvertFrom-Json
  }
  catch {
    Fail "InputPath must contain valid JSON: $input"
  }

  if (-not $source.PSObject.Properties.Name.Contains("task_id") -or [string]::IsNullOrWhiteSpace($source.task_id)) {
    Fail "InputPath JSON must include task_id"
  }

  if (-not $source.PSObject.Properties.Name.Contains("slices") -or -not ($source.slices -is [System.Array]) -or @($source.slices).Count -le 0) {
    Fail "InputPath JSON must include a non-empty slices array"
  }

  $seenWritePaths = @{}
  $slices = @()

  foreach ($slice in @($source.slices)) {
    foreach ($field in @("id", "goal", "exclusive_write")) {
      if (-not $slice.PSObject.Properties.Name.Contains($field)) {
        Fail "Each slice must include $field"
      }
    }

    $sliceWrites = @($slice.exclusive_write | ForEach-Object { Normalize-RepoPath -Path $_ -FieldName "slice.exclusive_write" })

    foreach ($writePath in $sliceWrites) {
      if ($seenWritePaths.ContainsKey($writePath)) {
        Fail "Duplicate exclusive_write path in decomposition: $writePath"
      }

      $seenWritePaths[$writePath] = $slice.id
    }

    $slices += [ordered]@{
      id = $slice.id
      goal = $slice.goal
      exclusive_write = @($sliceWrites)
      status = "planned"
    }
  }

  $decomposition = [ordered]@{
    schema_version = "1"
    task_id = $source.task_id
    generated_by = "specbridge-cli"
    slices = @($slices)
  }

  Write-Utf8JsonFile -Path $output -Value $decomposition -Depth 8

  Write-CliJson ([ordered]@{
    command = "decompose-task"
    ok = $true
    output_path = $output
    slices = @($slices).Count
  })

  exit 0
}

function Invoke-PrepareExecutorsCommand {
  $input = Normalize-RepoPath -Path $InputPath -FieldName "InputPath"
  $outputDir = ".specbridge/executor-packets"

  if (-not [string]::IsNullOrWhiteSpace($OutputDirectory)) {
    $outputDir = Normalize-RepoPath -Path $OutputDirectory -FieldName "OutputDirectory"
  }

  if ($outputDir -notmatch "^\.specbridge/executor-packets(/.*)?$") {
    Fail "OutputDirectory must be under .specbridge/executor-packets: $outputDir"
  }

  if (-not (Test-Path -LiteralPath $input)) {
    Fail "InputPath does not exist: $input"
  }

  try {
    $source = Get-Content -LiteralPath $input -Raw -Encoding UTF8 | ConvertFrom-Json
  }
  catch {
    Fail "InputPath must contain valid JSON: $input"
  }

  $taskId = Get-RequiredJsonString -Object $source -FieldName "task_id" -Context "InputPath JSON"

  if (-not $source.PSObject.Properties.Name.Contains("slices") -or -not ($source.slices -is [System.Array]) -or @($source.slices).Count -le 0) {
    Fail "InputPath JSON must include a non-empty slices array"
  }

  $safeTaskId = Convert-ToSafeName -Value $taskId -FieldName "task_id"
  $safeBranchPrefix = Convert-ToSafeName -Value $BranchPrefix -FieldName "BranchPrefix"
  $seenPacketPaths = @{}
  $seenBranchNames = @{}
  $packets = @()

  foreach ($slice in @($source.slices)) {
    $context = "slice"
    $sliceId = Get-RequiredJsonString -Object $slice -FieldName "id" -Context $context
    $goal = Get-RequiredJsonString -Object $slice -FieldName "goal" -Context $context
    $role = Get-RequiredJsonString -Object $slice -FieldName "role" -Context $context
    $contractPath = Normalize-RepoPath -Path (Get-RequiredJsonString -Object $slice -FieldName "contract_path" -Context $context) -FieldName "slice.contract_path"
    $finalReportPath = Normalize-RepoPath -Path (Get-RequiredJsonString -Object $slice -FieldName "final_report_path" -Context $context) -FieldName "slice.final_report_path"
    $exclusiveWrite = @(
      Get-RequiredJsonStringArray -Object $slice -FieldName "exclusive_write" -Context $context |
        ForEach-Object { Normalize-RepoPath -Path $_ -FieldName "slice.exclusive_write" }
    )
    $readOnly = @(
      Get-OptionalJsonStringArray -Object $slice -FieldName "read_only" -Context $context |
        ForEach-Object { Normalize-RepoPath -Path $_ -FieldName "slice.read_only" }
    )
    $validations = @(
      Get-RequiredJsonStringArray -Object $slice -FieldName "required_validations" -Context $context
    )

    if ($contractPath -notmatch "^\.specbridge/contracts/.+\.execution\.md$") {
      Fail "slice.contract_path must point to a SpecBridge execution contract: $contractPath"
    }

    if (-not (Test-Path -LiteralPath $contractPath)) {
      Fail "slice.contract_path does not exist: $contractPath"
    }

    if ($finalReportPath -notmatch "^\.specbridge/reports/.+\.final-report\.json$") {
      Fail "slice.final_report_path must point to a SpecBridge final report path: $finalReportPath"
    }

    $safeSliceId = Convert-ToSafeName -Value $sliceId -FieldName "slice.id"
    $branchName = "$safeBranchPrefix/$safeTaskId-$safeSliceId"

    if ($slice.PSObject.Properties.Name.Contains("branch_name") -and -not [string]::IsNullOrWhiteSpace($slice.branch_name)) {
      $branchName = $slice.branch_name.Trim()
    }

    if ($branchName -notmatch "^[A-Za-z0-9._/-]+$" -or $branchName -match "(^|/)\.\.(/|$)") {
      Fail "slice.branch_name contains unsupported characters: $branchName"
    }

    if ($seenBranchNames.ContainsKey($branchName)) {
      Fail "Duplicate branch_name in executor handoff input: $branchName"
    }

    $seenBranchNames[$branchName] = $sliceId
    $packetFileName = "$safeTaskId-$safeSliceId.executor-packet.json"
    $packetPath = Normalize-RepoPath -Path (Join-Path $outputDir $packetFileName) -FieldName "executor_packet_path"

    if ($seenPacketPaths.ContainsKey($packetPath)) {
      Fail "Duplicate executor packet path: $packetPath"
    }

    if ((Test-Path -LiteralPath $packetPath) -and -not $Force) {
      Fail "Executor packet already exists; use -Force to replace it: $packetPath"
    }

    $seenPacketPaths[$packetPath] = $sliceId

    $packet = [ordered]@{
      schema_version = "1"
      packet_id = "$safeTaskId-$safeSliceId"
      task_id = $taskId
      slice_id = $sliceId
      agent_role = $role
      goal = $goal
      launch_mode = "manual_antigravity"
      branch_name = $branchName
      execution_contract_path = $contractPath
      final_report_path = $finalReportPath
      exclusive_write = @($exclusiveWrite)
      read_only = @($readOnly)
      required_validations = @($validations)
      stop_conditions = @(
        "policy_conflict",
        "scope_conflict",
        "missing_required_context",
        "impossible_acceptance_criteria",
        "protected_resource_required"
      )
      status = "ready_for_handoff"
      source_files = @(
        $input,
        $contractPath
      )
      generated_by = "specbridge-cli"
    }

    Write-Utf8JsonFile -Path $packetPath -Value $packet -Depth 8
    $packets += $packetPath
  }

  Write-CliJson ([ordered]@{
    command = "prepare-executors"
    ok = $true
    output_directory = $outputDir
    packets = @($packets)
    packet_count = @($packets).Count
  })

  exit 0
}

