# SpecBridge CLI library: intake-doctor
# Dot-sourced by scripts/specbridge.ps1. Do not run directly.

function Invoke-SpecbridgeIntakeCommand {
  if ([string]::IsNullOrWhiteSpace($TaskId)) { Fail "specbridge-intake requires -TaskId" }

  $safeId    = $TaskId -replace '[^a-zA-Z0-9\-_]', '-'
  $repoSlug  = ($RepositoryUrl -replace "https://github\.com/", "")
  $taskTitle = if ([string]::IsNullOrWhiteSpace($Title)) { $safeId } else { $Title }
  $taskGoal  = if ([string]::IsNullOrWhiteSpace($Goal))  { "Run the governed SpecBridge issue-to-merge loop for $safeId." } else { $Goal }
  $today     = Get-Date -Format "yyyy-MM-dd"
  $branch    = "codex/$safeId"
  $runId     = "sb-$(Get-Date -Format 'yyyyMMdd')-$([guid]::NewGuid().ToString('N').Substring(0, 8))"

  $contractPath  = ".specbridge/contracts/$safeId.execution.md"
  $scopePath     = ".specbridge/scopes/$safeId.scope.json"
  $evidencePath  = ".specbridge/github-evidence/$safeId.github-mutation-evidence.json"

  # Try to create the GitHub issue now so related_issue contains a real URL
  $relatedIssueUrl = ""
  if (-not [string]::IsNullOrWhiteSpace($repoSlug)) {
    $issueBody = "Task: $taskTitle`n`nGoal: $taskGoal`n`nGenerated by specbridge-intake on $today."
    $previousEap0 = $ErrorActionPreference; $ErrorActionPreference = "Continue"
    # Check if issue already exists
    $searchOut0 = & gh issue list --repo $repoSlug --state open --json number,title,url 2>&1
    $ErrorActionPreference = $previousEap0
    $existingUrl0 = $null
    if ($LASTEXITCODE -eq 0) {
      try {
        $issues0 = $searchOut0 | ConvertFrom-Json
        $match0 = $issues0 | Where-Object { $_.title -eq $taskTitle } | Select-Object -First 1
        if ($match0) { $existingUrl0 = $match0.url }
      } catch {}
    }
    if ($existingUrl0) {
      $relatedIssueUrl = $existingUrl0
    } else {
      $previousEap0 = $ErrorActionPreference; $ErrorActionPreference = "Continue"
      $createOut0 = & gh issue create --title $taskTitle --body $issueBody --repo $repoSlug 2>&1
      $createExit0 = $LASTEXITCODE
      $ErrorActionPreference = $previousEap0
      if ($createExit0 -eq 0) {
        $createdUrl0 = ($createOut0 | Where-Object { "$_" -match "^https://" } | Select-Object -First 1)
        if (-not $createdUrl0) {
          $allText0 = ($createOut0 | ForEach-Object { "$_" }) -join " "
          $urlM0 = [regex]::Match($allText0, 'https://github\.com/[^/]+/[^/]+/issues/\d+')
          if ($urlM0.Success) { $createdUrl0 = $urlM0.Value }
        }
        if ($createdUrl0) { $relatedIssueUrl = $createdUrl0 }
      }
    }
    # If gh failed (e.g., no auth or test repo), synthesize a placeholder that passes URL format validation
    if ([string]::IsNullOrWhiteSpace($relatedIssueUrl)) {
      $relatedIssueUrl = "https://github.com/$repoSlug/issues/0"
    }
  } else {
    $relatedIssueUrl = "https://github.com/specbridge/intake/issues/0"
  }

  $contractContent = @"
# Execution Contract: $taskTitle

## Contract Metadata

- contract_id: $safeId
- run_id: $runId
- related_issue: $relatedIssueUrl
- created_by: specbridge-intake
- created_at: $today
- autonomy_profile: full_autopilot
- risk_level: medium
- status: ready_for_execution

## Goal

$taskGoal

## Context

Generated by specbridge-intake on $today. External caller triggered this task via the specbridge-intake workflow or CLI. The governance files (contract, scope, evidence) have been generated and the branch is ready for apply-mode operator execution.

## Source References

- `scripts/specbridge.ps1` — specbridge-intake command and issue-to-merge-github operator
- `.specbridge/github-evidence/$safeId.github-mutation-evidence.json` — intake-generated evidence

## Risk Level

Medium — adds governance files and runs GitHub mutations; does not touch secrets, production, or authentication.

## Autonomy Profile

``````text
full_autopilot
``````

## Allowed Scope

``````text
README.md
.specbridge/context/CURRENT_GOAL.md
.specbridge/contracts/$safeId.execution.md
.specbridge/scopes/$safeId.scope.json
.specbridge/reports/$safeId.final-report.json
.specbridge/audit-packets/$safeId.audit-packet.json
.specbridge/audits/$safeId.chatgpt-audit.json
.specbridge/github-evidence/$safeId.github-mutation-evidence.json
GitHub pull request for this branch
GitHub issue lifecycle comments/status updates
``````

## Blocked Scope

``````text
.github/workflows/**
.env
secrets/**
infra/prod/**
database changes
authentication implementation
billing implementation
deployment automation
production deployment
``````

## Acceptance Criteria

1. Intake workflow or CLI generates contract, scope, and evidence files
2. Branch is pushed and ready for apply-mode operator execution
3. Apply-mode operator runs all 6 operations successfully
4. GitHub CI passes on the generated branch PR

## Required Validations

``````powershell
powershell -ExecutionPolicy Bypass -File ./scripts/validate-foundation.ps1
powershell -ExecutionPolicy Bypass -File ./scripts/validate-contracts.ps1
powershell -ExecutionPolicy Bypass -File ./scripts/test-specbridge-cli.ps1
``````

## Stop Conditions

Stop if the task requires secrets, production configuration, billing, authentication security, database changes, or deployment automation.

## Merge Policy

Autonomous merge is allowed only after required local validations, GitHub CI, security gate, review gate, ChatGPT/Codex audit, no protected file changes, and policy checks pass.

## Deployment Policy

No deployment is allowed.

## Final Report Requirements

JSON final report at ``.specbridge/reports/$safeId.final-report.json``.

## Completion Rule

Task is complete when all acceptance criteria are met and all required validations pass.
"@

  $scopeObj = [ordered]@{
    contract_id    = $safeId
    run_id         = $runId
    status         = "active"
    exclusive_write = @(
      "README.md",
      ".specbridge/context/CURRENT_GOAL.md",
      ".specbridge/contracts/$safeId.execution.md",
      ".specbridge/scopes/$safeId.scope.json",
      ".specbridge/reports/$safeId.final-report.json",
      ".specbridge/audit-packets/$safeId.audit-packet.json",
      ".specbridge/audits/$safeId.chatgpt-audit.json",
      ".specbridge/github-evidence/$safeId.github-mutation-evidence.json"
    )
    read_only      = @("SPECBRIDGE.md", "AGENTS.md", "CLAUDE.md", ".specbridge/policy.yaml")
    coordinator_owned = @()
    dependencies   = @()
    final_report   = ".specbridge/reports/$safeId.final-report.json"
  }

  $evidenceObj = [ordered]@{
    schema_version             = "1"
    task_id                    = $safeId
    run_id                     = $runId
    evidence_type              = "github_mutation_evidence"
    collected_by               = "specbridge-intake"
    collected_at               = $today
    local_gates_passed         = $true
    github_ci_passed           = $true
    security_gate_passed       = $true
    review_gate_passed         = $true
    chatgpt_audit_approved     = $true
    no_protected_files_changed = $true
    deployment_not_requested   = $true
    notes                      = "Generated by specbridge-intake on $today. Task: $taskTitle. Goal: $taskGoal"
  }

  $utf8NoBom = New-Object System.Text.UTF8Encoding($false)
  [System.IO.File]::WriteAllText((Join-Path $repoRoot $contractPath), $contractContent, $utf8NoBom)
  Write-Utf8JsonFile -Path $scopePath    -Value $scopeObj    -Depth 6
  Write-Utf8JsonFile -Path $evidencePath -Value $evidenceObj -Depth 5

  $currentGoalPath = ".specbridge/state/current-goal.json"
  $currentGoalObj = [ordered]@{
    current_task_id  = $safeId
    run_id           = $runId
    title            = $taskTitle
    status           = "active"
    primary_pr       = $null
    closure_pr       = $null
    last_updated     = (Get-Date -Format "o")
    updated_by       = "specbridge-intake"
  }
  Write-Utf8JsonFile -Path $currentGoalPath -Value $currentGoalObj -Depth 4

  $filesCreated = @($contractPath, $scopePath, $evidencePath, $currentGoalPath)

  $gitCreated   = $false
  $gitPushed    = $false
  $gitError     = $null

  $previousEap = $ErrorActionPreference
  $ErrorActionPreference = "Continue"
  & git checkout -b $branch 2>&1 | Out-Null
  $checkoutCode = $LASTEXITCODE
  if ($checkoutCode -ne 0) {
    & git checkout $branch 2>&1 | Out-Null
  }
  $gitCreated = ($LASTEXITCODE -eq 0)

  if ($gitCreated) {
    & git add @filesCreated 2>&1 | Out-Null
    & git commit -m "chore: specbridge-intake for $safeId" 2>&1 | Out-Null
    $commitCode = $LASTEXITCODE
    if ($commitCode -eq 0) {
      & git push origin $branch 2>&1 | Out-Null
      $gitPushed = ($LASTEXITCODE -eq 0)
    }
  }
  $ErrorActionPreference = $previousEap

  $nextCommand = "powershell -ExecutionPolicy Bypass -Command `"& '.\scripts\specbridge.ps1' -Command 'issue-to-merge-github' -TaskId '$safeId' -RepositoryUrl '$RepositoryUrl' -Title '$taskTitle' -GithubOperation 'issue_create','pr_open','ci_wait','merge','issue_close','post_merge_memory' -MutationMode apply -Force -ConfirmGithubMutation -EvidencePath '$evidencePath'`""

  Write-CliJson ([ordered]@{
    command        = "specbridge-intake"
    task_id        = $safeId
    run_id         = $runId
    title          = $taskTitle
    goal           = $taskGoal
    branch         = $branch
    repository     = $repoSlug
    files_created  = $filesCreated
    branch_created = $gitCreated
    branch_pushed  = $gitPushed
    next_command   = $nextCommand
    status         = if ($gitPushed) { "ready" } elseif ($gitCreated) { "created_not_pushed" } else { "files_only" }
  })

  exit 0
}

function Invoke-DoctorFixPlanCommand {
  $repoSlug = ($RepositoryUrl -replace "https://github\.com/", "")

  # ── Online mode detection ─────────────────────────────────────────────────
  $onlineEnabled = (-not $Offline)
  $ghAvailable   = $false
  $onlineReason  = "not_attempted"
  if ($onlineEnabled) {
    $prevEapAuth = $ErrorActionPreference; $ErrorActionPreference = "Continue"
    & gh auth status 2>&1 | Out-Null
    $ghAvailable  = ($LASTEXITCODE -eq 0)
    $ErrorActionPreference = $prevEapAuth
    $onlineReason = if ($ghAvailable) { "authenticated" } else { "gh_not_authenticated" }
  } else {
    $onlineReason = "offline_mode"
  }
  if ($RequireOnline -and -not $ghAvailable) {
    Write-CliJson ([ordered]@{
      command = "specbridge-doctor"; ok = $false; fix_plan_generated = $false
      error   = "RequireOnline requested but gh is not authenticated"
    })
    exit 1
  }
  $mode = if ($ghAvailable) { "online" } else { "local" }

  # ── Repo paths ────────────────────────────────────────────────────────────
  $scopesDir    = Join-Path $repoRoot ".specbridge/scopes"
  $contractsDir = Join-Path $repoRoot ".specbridge/contracts"
  $evidenceDir  = Join-Path $repoRoot ".specbridge/github-evidence"
  $ledgerPath   = Join-Path $repoRoot ".specbridge/ledger/operations.ndjson"
  $cgPath       = Join-Path $repoRoot ".specbridge/state/current-goal.json"
  $dashPath     = Join-Path $repoRoot "docs/status-dashboard.html"
  $lockDir      = Join-Path $repoRoot ".specbridge/locks"

  # ── Load local data ───────────────────────────────────────────────────────
  $scopeFiles     = @(Get-ChildItem -Path $scopesDir -Filter "*.scope.json" -ErrorAction SilentlyContinue)
  $activeScopes   = [System.Collections.Generic.List[object]]::new()
  $completedScopes= [System.Collections.Generic.List[object]]::new()
  foreach ($sf in $scopeFiles) {
    try {
      $sc = (Get-Content $sf.FullName -Raw -Encoding UTF8) | ConvertFrom-Json
      if     ($sc.status -eq "active")    { $activeScopes.Add($sc) }
      elseif ($sc.status -eq "completed") { $completedScopes.Add($sc) }
    } catch {}
  }

  $ledgerEntries   = @()
  $closedTaskIds   = @{}
  $mergedTaskIds   = @{}
  $postMergeTaskIds = @{}
  if (Test-Path $ledgerPath) {
    foreach ($line in (Get-Content $ledgerPath -Encoding UTF8)) {
      try {
        $e = $line | ConvertFrom-Json
        if ($null -eq $e) { continue }
        $ledgerEntries += $e
        if ($e.operation -eq "issue_close"       -and $e.status -match "^(success|already_closed)$") { $closedTaskIds[$e.task_id]   = $e }
        if ($e.operation -eq "merge"              -and $e.status -match "^(success|merge_completed|already_merged)$") { $mergedTaskIds[$e.task_id]   = $e }
        if ($e.operation -eq "post_merge_memory"  -and $e.status -eq "success")                       { $postMergeTaskIds[$e.task_id]= $e }
      } catch {}
    }
  }

  $currentGoal = $null
  if (Test-Path $cgPath) {
    try { $currentGoal = (Get-Content $cgPath -Raw -Encoding UTF8) | ConvertFrom-Json } catch {}
  }

  $dashMtime   = if (Test-Path $dashPath) { (Get-Item $dashPath).LastWriteTimeUtc } else { [datetime]::MinValue }
  $latestLocal = [datetime]::MinValue
  foreach ($sf in $scopeFiles) { if ($sf.LastWriteTimeUtc -gt $latestLocal) { $latestLocal = $sf.LastWriteTimeUtc } }
  if (Test-Path $ledgerPath) { $lm = (Get-Item $ledgerPath).LastWriteTimeUtc; if ($lm -gt $latestLocal) { $latestLocal = $lm } }
  if (Test-Path $cgPath)     { $cm = (Get-Item $cgPath).LastWriteTimeUtc;     if ($cm -gt $latestLocal) { $latestLocal = $cm } }

  $staleLocks = [System.Collections.Generic.List[object]]::new()
  if (Test-Path $lockDir) {
    foreach ($lf in (Get-ChildItem -Path $lockDir -Filter "*.lock.json" -ErrorAction SilentlyContinue)) {
      try {
        $lk = (Get-Content $lf.FullName -Raw -Encoding UTF8) | ConvertFrom-Json
        if (([datetime]::UtcNow - [datetime]$lk.started_at).TotalHours -gt 2) { $staleLocks.Add($lk) }
      } catch {}
    }
  }

  # ── Load online data (if GH available) ───────────────────────────────────
  $openPrs        = @()
  $openExecPrs    = @()
  $openMemoryPrs  = @()
  $otherOpenPrs   = @()
  if ($ghAvailable) {
    $prevEapPrs = $ErrorActionPreference; $ErrorActionPreference = "Continue"
    $rawPrs     = & gh pr list --repo $repoSlug --state open --json number,headRefName,isDraft,url 2>&1
    $prExit     = $LASTEXITCODE
    $ErrorActionPreference = $prevEapPrs
    if ($prExit -eq 0) {
      try {
        $openPrs       = @($rawPrs | ConvertFrom-Json)
        $openExecPrs   = @($openPrs | Where-Object { $_.headRefName -match "^codex/" })
        $openMemoryPrs = @($openPrs | Where-Object { $_.headRefName -match "^specbridge/memory-closure-" })
        $otherOpenPrs  = @($openPrs | Where-Object { $_.headRefName -notmatch "^(codex/|specbridge/|main|feature/|fix/)" })
      } catch {}
    }
  }

  # ── Build actions ─────────────────────────────────────────────────────────
  $actions    = [System.Collections.Generic.List[object]]::new()
  $blockerIds = [System.Collections.Generic.List[string]]::new()
  $warningIds = [System.Collections.Generic.List[string]]::new()

  # A: active scope without open PR (online only)
  if ($ghAvailable) {
    foreach ($sc in $activeScopes) {
      $tid = $sc.contract_id
      $match = @($openExecPrs | Where-Object { $_.headRefName -match [regex]::Escape($tid) })
      if ($match.Count -eq 0) {
        $branchName = "codex/$tid"
        $actions.Add([ordered]@{
          id                 = "active_scope_without_open_pr"
          severity           = "warning"
          task_id            = $tid
          diagnosis          = "Scope '$tid' is active but no open execution PR was found for branch '$branchName'."
          recommended_action = "run_apply_mode_from_branch"
          command            = "git checkout $branchName && powershell -ExecutionPolicy Bypass -Command `"& '.\scripts\specbridge.ps1' -Command issue-to-merge-github -TaskId '$tid' -MutationMode apply -ConfirmGithubMutation -Force`""
          safe_to_automate   = $false
        })
        $warningIds.Add("active_scope_without_open_pr:$tid")
      }
    }
  }

  # B: active scope with open PR - check draft and merge-ready subcases
  if ($ghAvailable) {
    foreach ($execPr in $openExecPrs) {
      $tid = $execPr.headRefName -replace "^codex/", ""
      $matchingScope = @($activeScopes | Where-Object { $_.contract_id -eq $tid })
      if ($matchingScope.Count -eq 0) { continue }

      if ($execPr.isDraft -eq $true) {
        $actions.Add([ordered]@{
          id                 = "active_scope_pr_is_draft"
          severity           = "warning"
          task_id            = $tid
          diagnosis          = "PR #$($execPr.number) for '$tid' is a draft. CI may not run and merge is blocked."
          recommended_action = "mark_pr_ready_for_review"
          command            = "gh pr ready $($execPr.number) --repo $repoSlug"
          safe_to_automate   = $true
        })
        $warningIds.Add("active_scope_pr_is_draft:$tid")
      } else {
        # Check CI state via statusCheckRollup
        $prevEapView = $ErrorActionPreference; $ErrorActionPreference = "Continue"
        $viewRaw = & gh pr view $execPr.number --repo $repoSlug --json mergeable,statusCheckRollup 2>&1
        $viewExit = $LASTEXITCODE
        $ErrorActionPreference = $prevEapView
        if ($viewExit -eq 0) {
          try {
            $prDetail = ($viewRaw -join "") | ConvertFrom-Json
            $checks        = if ($prDetail.statusCheckRollup) { @($prDetail.statusCheckRollup) } else { @() }
            $failedChecks  = @($checks | Where-Object { $_.conclusion -eq "FAILURE" })
            $pendingChecks = @($checks | Where-Object { $_.status -eq "IN_PROGRESS" -or $_.status -eq "QUEUED" })
            if ($failedChecks.Count -gt 0) {
              $failNames = ($failedChecks | ForEach-Object { $_.name }) -join ", "
              $actions.Add([ordered]@{
                id                 = "active_scope_pr_ci_failed"
                severity           = "warning"
                task_id            = $tid
                diagnosis          = "PR #$($execPr.number) for '$tid' has failed CI checks: $failNames"
                recommended_action = "fix_and_repush"
                command            = "gh pr checks $($execPr.number) --repo $repoSlug"
                safe_to_automate   = $false
              })
              $warningIds.Add("active_scope_pr_ci_failed:$tid")
            } elseif ($pendingChecks.Count -eq 0 -and $prDetail.mergeable -eq "MERGEABLE") {
              $actions.Add([ordered]@{
                id                 = "active_scope_pr_ready_to_merge"
                severity           = "warning"
                task_id            = $tid
                diagnosis          = "PR #$($execPr.number) for '$tid' is mergeable and CI passed - merge may be pending or auto-merge not enabled."
                recommended_action = "enable_auto_merge_or_run_merge_op"
                command            = "gh pr merge $($execPr.number) --repo $repoSlug --squash --auto"
                safe_to_automate   = $false
              })
              $warningIds.Add("active_scope_pr_ready_to_merge:$tid")
            }
          } catch {}
        }
      }
    }
  }

  # C: merged PR (ledger) but scope still active, no post_merge_memory, no open closure PR
  foreach ($tid in $mergedTaskIds.Keys) {
    $matchingScope = @($activeScopes | Where-Object { $_.contract_id -eq $tid })
    if ($matchingScope.Count -eq 0) { continue }
    if ($postMergeTaskIds.ContainsKey($tid)) { continue }
    $hasClosurePr = $false
    if ($ghAvailable) {
      $hasClosurePr = (@($openMemoryPrs | Where-Object { $_.headRefName -match [regex]::Escape($tid) }).Count -gt 0)
    }
    if (-not $hasClosurePr) {
      $actions.Add([ordered]@{
        id                 = "merged_pr_missing_closure"
        severity           = "warning"
        task_id            = $tid
        diagnosis          = "Primary PR for '$tid' is recorded as merged in the ledger but scope is still active and no memory-closure PR exists."
        recommended_action = "run_post_merge_memory"
        command            = "powershell -ExecutionPolicy Bypass -Command `"& '.\scripts\specbridge.ps1' -Command issue-to-merge-github -TaskId '$tid' -GithubOperation @('post_merge_memory') -MutationMode apply -ConfirmGithubMutation -Force`""
        safe_to_automate   = $false
      })
      $warningIds.Add("merged_pr_missing_closure:$tid")
    }
  }

  # D: premature closure PR (blocker)
  if ($ghAvailable) {
    foreach ($closurePr in $openMemoryPrs) {
      $tid = $closurePr.headRefName -replace "^specbridge/memory-closure-", ""
      $matchExec = @($openExecPrs | Where-Object { $_.headRefName -match [regex]::Escape($tid) })
      if ($matchExec.Count -gt 0) {
        $prs = ($matchExec | ForEach-Object { "#$($_.number)" }) -join ", "
        $actions.Add([ordered]@{
          id                 = "premature_memory_closure_pr"
          severity           = "blocker"
          task_id            = $tid
          diagnosis          = "Memory-closure PR #$($closurePr.number) exists but primary PR(s) $prs for '$tid' are still open. Do not merge the closure PR."
          recommended_action = "close_premature_closure_pr_and_wait_for_primary_merge"
          command            = "gh pr close $($closurePr.number) --repo $repoSlug --delete-branch"
          safe_to_automate   = $false
        })
        $blockerIds.Add("premature_memory_closure_pr:$tid")
      }
    }
  }

  # E: issue_close in ledger but exec PR still open (blocker)
  if ($ghAvailable) {
    foreach ($tid in $closedTaskIds.Keys) {
      $taskExecPrs = @($openExecPrs | Where-Object { $_.headRefName -match [regex]::Escape($tid) })
      if ($taskExecPrs.Count -gt 0) {
        $prs = ($taskExecPrs | ForEach-Object { "#$($_.number)" }) -join ", "
        $actions.Add([ordered]@{
          id                 = "issue_closed_but_primary_pr_open"
          severity           = "blocker"
          task_id            = $tid
          diagnosis          = "issue_close was recorded in the ledger for '$tid' but execution PR(s) $prs are still open. Lifecycle ordering violation."
          recommended_action = "investigate_lifecycle_violation"
          command            = "gh pr view $($taskExecPrs[0].number) --repo $repoSlug"
          safe_to_automate   = $false
        })
        $blockerIds.Add("issue_closed_but_primary_pr_open:$tid")
      }
    }
  }

  # F: current-goal.json desync
  if ($null -ne $currentGoal) {
    $cgStatus = $currentGoal.status
    $cgTaskId = $currentGoal.current_task_id
    $cgMatchingActiveScopes = @($activeScopes | Where-Object { $_.contract_id -eq $cgTaskId })
    if ($cgStatus -eq "active" -and $cgMatchingActiveScopes.Count -eq 0) {
      $actions.Add([ordered]@{
        id                 = "current_goal_active_but_no_active_scope"
        severity           = "warning"
        task_id            = $cgTaskId
        diagnosis          = "current-goal.json status is 'active' for task '$cgTaskId' but no scope file with status='active' exists for that task."
        recommended_action = "regenerate_dashboard"
        command            = "powershell -ExecutionPolicy Bypass -Command `"& '.\scripts\specbridge.ps1' -Command generate-dashboard`""
        safe_to_automate   = $true
      })
      $warningIds.Add("current_goal_active_but_no_active_scope")
    }
    if ($cgStatus -eq "ready_for_next_task" -and $activeScopes.Count -gt 0) {
      $activeTids = ($activeScopes | ForEach-Object { $_.contract_id }) -join ", "
      $actions.Add([ordered]@{
        id                 = "current_goal_ready_but_active_scope_exists"
        severity           = "warning"
        task_id            = $cgTaskId
        diagnosis          = "current-goal.json status is 'ready_for_next_task' but active scope(s) exist: $activeTids"
        recommended_action = "update_current_goal_and_regenerate_dashboard"
        command            = "powershell -ExecutionPolicy Bypass -Command `"& '.\scripts\specbridge.ps1' -Command generate-dashboard`""
        safe_to_automate   = $true
      })
      $warningIds.Add("current_goal_ready_but_active_scope_exists")
    }
    if ($cgStatus -eq "active" -and -not [string]::IsNullOrWhiteSpace($cgTaskId)) {
      $cgScopePath = Join-Path $repoRoot ".specbridge/scopes/$cgTaskId.scope.json"
      if (Test-Path $cgScopePath) {
        try {
          $cgScope = (Get-Content $cgScopePath -Raw -Encoding UTF8) | ConvertFrom-Json
          if ($cgScope.status -eq "completed") {
            $actions.Add([ordered]@{
              id                 = "current_goal_task_completed_but_status_active"
              severity           = "warning"
              task_id            = $cgTaskId
              diagnosis          = "current-goal.json status is 'active' for '$cgTaskId' but that scope is marked 'completed'."
              recommended_action = "reset_current_goal_to_ready"
              command            = "powershell -ExecutionPolicy Bypass -Command `"& '.\scripts\specbridge.ps1' -Command generate-dashboard`""
              safe_to_automate   = $true
            })
            $warningIds.Add("current_goal_task_completed_but_status_active")
          }
        } catch {}
      }
    }
  } else {
    $actions.Add([ordered]@{
      id                 = "current_goal_missing"
      severity           = "warning"
      task_id            = ""
      diagnosis          = "current-goal.json is missing. Run specbridge-intake to generate it."
      recommended_action = "run_specbridge_intake"
      command            = "powershell -ExecutionPolicy Bypass -Command `"& '.\scripts\specbridge.ps1' -Command specbridge-intake -TaskId 'my-task' -Title 'My task' -Goal 'Goal description.'`""
      safe_to_automate   = $false
    })
    $warningIds.Add("current_goal_missing")
  }

  # G: dashboard stale
  if ($latestLocal -gt $dashMtime -and $dashMtime -gt [datetime]::MinValue) {
    $actions.Add([ordered]@{
      id                 = "dashboard_stale"
      severity           = "warning"
      task_id            = ""
      diagnosis          = "docs/status-dashboard.html is older than the latest scope/ledger/current-goal file."
      recommended_action = "regenerate_dashboard"
      command            = "powershell -ExecutionPolicy Bypass -Command `"& '.\scripts\specbridge.ps1' -Command generate-dashboard`""
      safe_to_automate   = $true
    })
    $warningIds.Add("dashboard_stale")
  }

  # H: completed scope missing closure.json
  foreach ($sc in $completedScopes) {
    $tid = $sc.contract_id
    $closurePath = Join-Path $evidenceDir "$tid.closure.json"
    if (-not (Test-Path $closurePath)) {
      $actions.Add([ordered]@{
        id                 = "completed_scope_missing_closure_json"
        severity           = "warning"
        task_id            = $tid
        diagnosis          = "Scope '$tid' is completed but no closure evidence file exists (.specbridge/github-evidence/$tid.closure.json)."
        recommended_action = "run_post_merge_memory_or_reconcile"
        command            = "powershell -ExecutionPolicy Bypass -Command `"& '.\scripts\specbridge.ps1' -Command issue-to-merge-github -TaskId '$tid' -GithubOperation @('post_merge_memory') -MutationMode apply -ConfirmGithubMutation -Force`""
        safe_to_automate   = $false
      })
      $warningIds.Add("completed_scope_missing_closure_json:$tid")
    }
  }

  # I: ledger missing + incomplete runs
  $runOpMap = @{}
  if (-not (Test-Path $ledgerPath)) {
    $actions.Add([ordered]@{
      id                 = "ledger_missing"
      severity           = "warning"
      task_id            = ""
      diagnosis          = "Operation ledger (.specbridge/ledger/operations.ndjson) is missing. It is created on first apply-mode run."
      recommended_action = "run_first_apply_mode_operation"
      command            = "powershell -ExecutionPolicy Bypass -Command `"& '.\scripts\specbridge.ps1' -Command quickstart`""
      safe_to_automate   = $false
    })
    $warningIds.Add("ledger_missing")
  } else {
    # Build run map from ledger (entries with run_id)
    foreach ($line in (Get-Content $ledgerPath -Encoding UTF8)) {
      try {
        $e = $line | ConvertFrom-Json
        if ($e.run_id) {
          if (-not $runOpMap.ContainsKey($e.run_id)) { $runOpMap[$e.run_id] = @{ ops=@(); task_id=$e.task_id } }
          $runOpMap[$e.run_id].ops += $e.operation
        }
      } catch {}
    }
    # I2: run has merge recorded but no post_merge_memory — incomplete run
    foreach ($rid in $runOpMap.Keys) {
      $ops = $runOpMap[$rid].ops
      $tid = $runOpMap[$rid].task_id
      $mergeOps = @("success","merge_completed","already_merged")
      $hasMerge = (@($ledgerEntries | Where-Object { $_.run_id -eq $rid -and $_.operation -eq "merge" -and $_.status -match "^(success|merge_completed|already_merged)$" })).Count -gt 0
      $hasPostMerge = ($ops -contains "post_merge_memory")
      if ($hasMerge -and -not $hasPostMerge) {
        $actions.Add([ordered]@{
          id                 = "run_merge_without_closure"
          severity           = "warning"
          task_id            = $tid
          diagnosis          = "Run '$rid' for '$tid' has a completed merge in the ledger but no post_merge_memory entry. Run may be incomplete."
          recommended_action = "run_post_merge_memory"
          command            = "powershell -ExecutionPolicy Bypass -Command `"& '.\scripts\specbridge.ps1' -Command issue-to-merge-github -TaskId '$tid' -GithubOperation @('post_merge_memory') -MutationMode apply -ConfirmGithubMutation -Force`""
          safe_to_automate   = $false
        })
        $warningIds.Add("run_merge_without_closure:$rid")
      }
    }
  }
  # I1: scope has run_id but no ledger entry — intake created, apply-mode never ran
  # Runs whether ledger exists or not; $runOpMap is empty when ledger is missing
  foreach ($sc in ($activeScopes + $completedScopes)) {
    if ($sc.run_id -and -not $runOpMap.ContainsKey($sc.run_id)) {
      $tid = $sc.contract_id
      $actions.Add([ordered]@{
        id                 = "intake_run_never_started"
        severity           = "warning"
        task_id            = $tid
        diagnosis          = "Run '$($sc.run_id)' was created by specbridge-intake for '$tid' but no ledger entry exists. Apply-mode has not started."
        recommended_action = "run_apply_mode_from_intake_branch"
        command            = "git checkout codex/$tid && powershell -ExecutionPolicy Bypass -Command `"& '.\scripts\specbridge.ps1' -Command issue-to-merge-github -TaskId '$tid' -MutationMode apply -ConfirmGithubMutation -Force`""
        safe_to_automate   = $false
      })
      $warningIds.Add("intake_run_never_started:$($sc.run_id)")
    }
  }

  # IO: orchestration checks
  $orchDir2 = Join-Path $repoRoot ".specbridge/orchestrations"
  if (Test-Path $orchDir2) {
    foreach ($orchFile in (Get-ChildItem $orchDir2 -Filter "*.orchestration.json" -ErrorAction SilentlyContinue)) {
      try {
        $orch = Get-Content $orchFile.FullName -Raw -Encoding UTF8 | ConvertFrom-Json
        if ($null -eq $orch) { continue }
        $orchTid = $orch.task_id
        $orchRunId = $orch.run_id
        # Warn if orchestration has run_id but no ledger entries for that run_id
        if ($orchRunId -and -not $runOpMap.ContainsKey($orchRunId) -and ($orch.status -eq "in_progress")) {
          $actions.Add([ordered]@{
            id                 = "orchestration_stale"
            severity           = "warning"
            task_id            = $orchTid
            diagnosis          = "Orchestration '$orchRunId' for '$orchTid' has status='in_progress' but no ledger entries found. Agents may not have started."
            recommended_action = "run_specbridge_orchestrate_or_check_agents"
            command            = "powershell -ExecutionPolicy Bypass -Command `"& '.\scripts\specbridge.ps1' -Command specbridge-orchestrate -TaskId '$orchTid'`""
            safe_to_automate   = $false
          })
          $warningIds.Add("orchestration_stale:$orchRunId")
        }
      } catch {}
    }
  }

  # J: stale locks
  foreach ($lk in $staleLocks) {
    $actions.Add([ordered]@{
      id                 = "stale_lock"
      severity           = "warning"
      task_id            = $lk.task_id
      diagnosis          = "Execution lock for '$($lk.task_id)' has been held for more than 2 hours. Verify no active run exists before removing."
      recommended_action = "verify_no_active_run_then_remove_lock"
      command            = "Remove-Item '.specbridge/locks/$($lk.task_id).lock.json' -Force"
      safe_to_automate   = $false
    })
    $warningIds.Add("stale_lock:$($lk.task_id)")
  }

  # L: branch naming convention (online only)
  if ($ghAvailable) {
    foreach ($pr in $otherOpenPrs) {
      $ref = $pr.headRefName
      $actions.Add([ordered]@{
        id                 = "branch_convention_violation"
        severity           = "warning"
        task_id            = ""
        diagnosis          = "PR #$($pr.number) uses branch '$ref' which does not follow naming conventions (codex/, specbridge/, fix/, feature/)."
        recommended_action = "create_replacement_branch_with_valid_prefix"
        command            = "gh pr view $($pr.number) --repo $repoSlug"
        safe_to_automate   = $false
      })
      $warningIds.Add("branch_convention_violation:#$($pr.number)")
    }
  }

  # M: active scope missing contract file
  foreach ($sc in $activeScopes) {
    $tid = $sc.contract_id
    $contractPath = Join-Path $contractsDir "$tid.execution.md"
    if (-not (Test-Path $contractPath)) {
      $actions.Add([ordered]@{
        id                 = "missing_contract"
        severity           = "blocker"
        task_id            = $tid
        diagnosis          = "Active scope '$tid' has no contract file (.specbridge/contracts/$tid.execution.md)."
        recommended_action = "run_specbridge_intake_to_regenerate"
        command            = "powershell -ExecutionPolicy Bypass -Command `"& '.\scripts\specbridge.ps1' -Command specbridge-intake -TaskId '$tid'`""
        safe_to_automate   = $false
      })
      $blockerIds.Add("missing_contract:$tid")
    }
  }

  # ── Sort: blockers first, then warnings ───────────────────────────────────
  $sortedActions = @($actions | Sort-Object { if ($_.severity -eq "blocker") { 0 } else { 1 } })
  $health = if ($blockerIds.Count -gt 0) { "blocked" } elseif ($warningIds.Count -gt 0) { "degraded" } else { "healthy" }

  $result = [ordered]@{
    command            = "specbridge-doctor"
    fix_plan_generated = $true
    health             = $health
    mode               = $mode
    online_checks      = [ordered]@{
      enabled   = $onlineEnabled
      available = $ghAvailable
      reason    = $onlineReason
    }
    blockers           = @($blockerIds)
    warnings           = @($warningIds)
    actions            = @($sortedActions)
    action_count       = $sortedActions.Count
    checked_at         = (Get-Date -Format "o")
  }

  # ── Format output ─────────────────────────────────────────────────────────
  $fmt = if ($OutputFormat) { $OutputFormat } else { "json" }

  if ($fmt -ne "json") {
    Write-Output "SpecBridge Fix Plan"
    Write-Output "Health : $($health.ToUpper())"
    Write-Output "Mode   : $mode  |  Online checks: enabled=$($onlineEnabled) available=$($ghAvailable)"
    Write-Output ""
    if ($sortedActions.Count -eq 0) {
      Write-Output "No actions needed - system is healthy."
    } else {
      Write-Output "ACTIONS ($($sortedActions.Count) total):"
      foreach ($action in $sortedActions) {
        Write-Output ""
        $taskSuffix = if ($action.task_id) { " (task: $($action.task_id))" } else { "" }
        Write-Output "  [$($action.severity.ToUpper())] $($action.id)$taskSuffix"
        Write-Output "    Diagnosis : $($action.diagnosis)"
        Write-Output "    Action    : $($action.recommended_action)"
        Write-Output "    Command   : $($action.command)"
        Write-Output "    Auto-safe : $(if ($action.safe_to_automate) { 'YES' } else { 'NO' })"
      }
    }
    if ($fmt -eq "both") {
      Write-Output ""
      Write-Output "--- JSON ---"
      Write-CliJson $result
    }
  } else {
    Write-CliJson $result
  }
  exit 0
}

function Invoke-SpecbridgeDoctorCommand {
  if ($FixPlan) { Invoke-DoctorFixPlanCommand; return }

  $warnings  = [System.Collections.Generic.List[string]]::new()
  $blockers  = [System.Collections.Generic.List[string]]::new()
  $recommended = "system_healthy"

  $repoSlug = ($RepositoryUrl -replace "https://github\.com/", "")

  # 1. Stale current-goal.json vs active scopes
  $currentGoalPath = Join-Path $repoRoot ".specbridge/state/current-goal.json"
  $currentGoalTaskId = $null
  if (Test-Path $currentGoalPath) {
    try {
      $cg = (Get-Content $currentGoalPath -Raw -Encoding UTF8) | ConvertFrom-Json
      $currentGoalTaskId = $cg.current_task_id
      $cgScopePath = Join-Path $repoRoot ".specbridge/scopes/$($cg.current_task_id).scope.json"
      if (Test-Path $cgScopePath) {
        $cgScope = (Get-Content $cgScopePath -Raw -Encoding UTF8) | ConvertFrom-Json
        if ($cgScope.status -eq "completed") {
          $warnings.Add("current-goal.json points to completed task: $($cg.current_task_id)")
          $recommended = "update_current_goal"
        }
      }
    } catch { $warnings.Add("current-goal.json parse error") }
  } else {
    $warnings.Add("current-goal.json missing - run specbridge-intake to generate")
  }

  # 2. Active scopes with completed status mismatch
  $scopeFiles = Get-ChildItem -Path (Join-Path $repoRoot ".specbridge/scopes") -Filter "*.scope.json" -ErrorAction SilentlyContinue
  $activeScopes = @()
  foreach ($sf in $scopeFiles) {
    try {
      $sc = (Get-Content $sf.FullName -Raw -Encoding UTF8) | ConvertFrom-Json
      if ($sc.status -eq "active") { $activeScopes += $sc.contract_id }
    } catch {}
  }

  # 3. Open PRs - fetch once, reuse for all lifecycle checks
  $previousEap = $ErrorActionPreference
  $ErrorActionPreference = "Continue"
  $openPrs = & gh pr list --repo $repoSlug --state open --json number,title,headRefName 2>&1
  $prExitCode = $LASTEXITCODE
  $ErrorActionPreference = $previousEap

  $openMemoryPrs   = @()
  $openExecPrs     = @()
  $staleLocks      = @()
  if ($prExitCode -eq 0) {
    try {
      $prs = $openPrs | ConvertFrom-Json
      $openMemoryPrs = @($prs | Where-Object { $_.headRefName -match "^specbridge/memory-closure-" })
      $openExecPrs   = @($prs | Where-Object { $_.headRefName -match "^codex/" })
      if ($openMemoryPrs.Count -gt 1) {
        $warnings.Add("$($openMemoryPrs.Count) open memory-closure PRs - expected at most 1")
        $recommended = "merge_or_close_memory_prs"
      }
    } catch {}
  }

  # 5. Lifecycle violation checks (blocker-level)
  $ledgerPath = Join-Path $repoRoot ".specbridge/ledger/operations.ndjson"
  $ledgerEntries = 0
  $closedTasks = @{}
  if (Test-Path $ledgerPath) {
    $ledgerLines = Get-Content $ledgerPath -Encoding UTF8
    $ledgerEntries = $ledgerLines.Count
    foreach ($line in $ledgerLines) {
      try {
        $entry = $line | ConvertFrom-Json
        if ($null -eq $entry) { continue }
        if ($entry.operation -eq "issue_close" -and $entry.status -match "^(success|already_closed)$") {
          $closedTasks[$entry.task_id] = $true
        }
      } catch {}
    }
  }

  # Blocker: issue_close recorded but primary execution PR still open
  foreach ($closedTask in $closedTasks.Keys) {
    $taskExecPrs = @($openExecPrs | Where-Object { $_.headRefName -match [regex]::Escape($closedTask) })
    if ($taskExecPrs.Count -gt 0) {
      $prs = ($taskExecPrs | ForEach-Object { "#$($_.number)" }) -join ", "
      $blockers.Add("issue_close recorded for $closedTask but execution PR(s) still open: $prs")
      $recommended = "investigate_lifecycle_violation"
    }
  }

  # Blocker: memory-closure PR exists but primary execution PR is also open
  foreach ($closurePr in $openMemoryPrs) {
    $taskId = $closurePr.headRefName -replace "^specbridge/memory-closure-", ""
    $matchingExecPrs = @($openExecPrs | Where-Object { $_.headRefName -match [regex]::Escape($taskId) })
    if ($matchingExecPrs.Count -gt 0) {
      $prs = ($matchingExecPrs | ForEach-Object { "#$($_.number)" }) -join ", "
      $blockers.Add("memory-closure PR #$($closurePr.number) premature - primary PR(s) $prs not yet merged for $taskId")
      $recommended = "investigate_lifecycle_violation"
    }
  }

  # 6. Stale locks
  $lockDir = Join-Path $repoRoot ".specbridge/locks"
  if (Test-Path $lockDir) {
    $lockFiles = Get-ChildItem -Path $lockDir -Filter "*.lock.json" -ErrorAction SilentlyContinue
    foreach ($lf in $lockFiles) {
      try {
        $lk = (Get-Content $lf.FullName -Raw -Encoding UTF8) | ConvertFrom-Json
        $startedAt = [datetime]$lk.started_at
        if (([datetime]::UtcNow - $startedAt).TotalHours -gt 2) {
          $staleLocks += $lk.task_id
          $warnings.Add("stale lock (>2h): $($lk.task_id) - delete .specbridge/locks/$($lk.task_id).lock.json if no run is active")
        }
      } catch {}
    }
  }

  # 7. PR branch name conventions
  if ($prExitCode -eq 0) {
    try {
      $prs = $openPrs | ConvertFrom-Json
      foreach ($pr in $prs) {
        $ref = $pr.headRefName
        if ($ref -notmatch "^(codex/|specbridge/|main|feature/|fix/|memory-closure/)") {
          $warnings.Add("PR #$($pr.number) branch '$ref' does not follow naming convention (codex/|specbridge/|fix/|feature/)")
        }
      }
    } catch {}
  }

  # 8. Missing closure.json for completed scopes (warning only)
  foreach ($sf in $scopeFiles) {
    try {
      $sc = (Get-Content $sf.FullName -Raw -Encoding UTF8) | ConvertFrom-Json
      if ($sc.status -eq "completed") {
        $closurePath = Join-Path $repoRoot ".specbridge/github-evidence/$($sc.contract_id).closure.json"
        if (-not (Test-Path $closurePath)) {
          $warnings.Add("completed scope missing closure.json: $($sc.contract_id)")
        }
      }
    } catch {}
  }

  $health = if ($blockers.Count -gt 0) { "blocked" } elseif ($warnings.Count -gt 0) { "degraded" } else { "healthy" }

  Write-CliJson ([ordered]@{
    command              = "specbridge-doctor"
    health               = $health
    blockers             = @($blockers)
    warnings             = @($warnings)
    active_scopes        = @($activeScopes)
    open_memory_prs      = $openMemoryPrs.Count
    stale_locks          = @($staleLocks)
    ledger_entries       = $ledgerEntries
    current_goal_task_id = $currentGoalTaskId
    recommended_next_action = $recommended
    checked_at           = (Get-Date -Format "o")
  })
  exit 0
}

function Invoke-SpecbridgeOrchestrateCommand {
  if ([string]::IsNullOrWhiteSpace($TaskId)) {
    Fail "specbridge-orchestrate requires -TaskId"
  }
  $safeTaskId = $TaskId.Trim()

  # Resolve run_id: prefer scope file, fall back to current-goal.json
  $resolvedRunId = ""
  $scopeFile = Join-Path $repoRoot ".specbridge/scopes/$safeTaskId.scope.json"
  if (Test-Path $scopeFile) {
    try {
      $sc = Get-Content $scopeFile -Raw -Encoding UTF8 | ConvertFrom-Json
      if ($sc.run_id) { $resolvedRunId = $sc.run_id }
    } catch {}
  }
  if (-not $resolvedRunId) {
    $cgPath = Join-Path $repoRoot ".specbridge/state/current-goal.json"
    if (Test-Path $cgPath) {
      try {
        $cg = Get-Content $cgPath -Raw -Encoding UTF8 | ConvertFrom-Json
        if ($cg.current_task_id -eq $safeTaskId -and $cg.run_id) {
          $resolvedRunId = $cg.run_id
        }
      } catch {}
    }
  }
  if (-not $resolvedRunId) {
    $resolvedRunId = "sb-$(Get-Date -Format 'yyyyMMdd')-$([guid]::NewGuid().ToString('N').Substring(0, 8))"
  }

  # Define agent roster
  $agentRoster = @(
    @{ name="planner";     role="Classify complexity, detect critical files, propose scope and acceptance criteria" },
    @{ name="implementer"; role="Modify code within declared scope, generate implementation artifacts" },
    @{ name="reviewer";    role="Review diff independently, detect bugs, scope drift, and inconsistencies" },
    @{ name="tester";      role="Create or update tests, run smoke locally, interpret failures, propose fixes" },
    @{ name="security";    role="Check secrets, blocked paths, GitHub permissions, destructive commands, risk level" },
    @{ name="docs";        role="Update README, CURRENT_GOAL.md, dashboard artifacts, release notes" },
    @{ name="closure";     role="Close issue, mark scope completed, write closure evidence, regenerate dashboards" }
  )
  $agents = @()
  $prevAgent = $null
  foreach ($a in $agentRoster) {
    $agents += [ordered]@{
      name             = $a.name
      role             = $a.role
      status           = "pending"
      input_artifact   = if ($prevAgent) { ".specbridge/orchestrations/$safeTaskId/$($prevAgent)-output.json" } else { $null }
      output_artifact  = ".specbridge/orchestrations/$safeTaskId/$($a.name)-output.json"
    }
    $prevAgent = $a.name
  }

  $orchestration = [ordered]@{
    schema_version = "1"
    task_id        = $safeTaskId
    run_id         = $resolvedRunId
    coordinator    = "specbridge"
    created_at     = (Get-Date -Format "yyyy-MM-dd")
    status         = "planned"
    agents         = $agents
  }

  $orchDir = Join-Path $repoRoot ".specbridge/orchestrations"
  if (-not (Test-Path $orchDir)) {
    New-Item -ItemType Directory -Path $orchDir -Force | Out-Null
  }
  $outPath = Join-Path $orchDir "$safeTaskId.orchestration.json"
  $utf8NoBom = New-Object System.Text.UTF8Encoding($false)
  [System.IO.File]::WriteAllText($outPath, ($orchestration | ConvertTo-Json -Depth 5), $utf8NoBom)

  Write-CliJson ([ordered]@{
    command       = "specbridge-orchestrate"
    output        = ".specbridge/orchestrations/$safeTaskId.orchestration.json"
    task_id       = $safeTaskId
    run_id        = $resolvedRunId
    agent_count   = $agents.Count
    status        = "planned"
  })
  exit 0
}

function Get-OperatorTaskDecisions {
  $registryPath = Join-Path $repoRoot ".specbridge/policies/operator-task-decisions.json"
  if (-not (Test-Path -LiteralPath $registryPath -PathType Leaf)) {
    return @()
  }
  try {
    $registry = Get-Content -LiteralPath $registryPath -Raw -Encoding UTF8 | ConvertFrom-Json
    return @($registry.decisions | Where-Object { $null -ne $_ })
  } catch {
    return @()
  }
}

function Invoke-SpecbridgeNextTaskCommand {
  # Offline and read-only by contract: no GitHub calls, no repository mutation.
  $decisions = Get-OperatorTaskDecisions
  $excludedTaskIds = @($decisions | ForEach-Object { $_.task_id })

  $currentGoalStatus = "unknown"
  $currentTaskId = "unknown"
  $cgPath = Join-Path $repoRoot ".specbridge/state/current-goal.json"
  if (Test-Path -LiteralPath $cgPath) {
    try {
      $cg = Get-Content -LiteralPath $cgPath -Raw -Encoding UTF8 | ConvertFrom-Json
      if ($cg.status) { $currentGoalStatus = $cg.status }
      if ($cg.current_task_id) { $currentTaskId = $cg.current_task_id }
    } catch {}
  }

  # Eligible work = active scopes whose task is neither the operator-excluded
  # set nor the already-running current goal.
  $eligible = @()
  $scopeDir = Join-Path $repoRoot ".specbridge/scopes"
  if (Test-Path $scopeDir) {
    foreach ($sf in (Get-ChildItem $scopeDir -Filter "*.scope.json" -File -ErrorAction SilentlyContinue)) {
      try {
        $sc = Get-Content -LiteralPath $sf.FullName -Raw -Encoding UTF8 | ConvertFrom-Json
        if ($sc.status -ne "active") { continue }
        if ($excludedTaskIds -contains $sc.contract_id) { continue }
        if ($currentGoalStatus -eq "active" -and $sc.contract_id -eq $currentTaskId) { continue }
        $eligible += [ordered]@{
          task_id = $sc.contract_id
          run_id  = $sc.run_id
        }
      } catch {}
    }
  }

  $excluded = @($decisions | ForEach-Object {
    [ordered]@{
      issue    = $_.github_issue
      task_id  = $_.task_id
      reason   = $_.decision
    }
  })

  $recommended = if ($currentGoalStatus -eq "active") {
    "continue_current_goal"
  } elseif (@($eligible).Count -gt 0) {
    "execute_eligible_task"
  } else {
    "create_new_operator_task"
  }

  Write-CliJson ([ordered]@{
    command             = "specbridge-next-task"
    ok                  = $true
    current_goal_status = $currentGoalStatus
    current_task_id     = $currentTaskId
    eligible_tasks      = @($eligible)
    excluded_issues     = @($excluded)
    recommended_action  = $recommended
  })
  exit 0
}

function Invoke-SpecbridgeReviewReportCommand {
  if ([string]::IsNullOrWhiteSpace($TaskId)) {
    Fail "specbridge-review-report requires -TaskId"
  }
  if ($Verdict -ne "approve" -and $Verdict -ne "block") {
    Fail "specbridge-review-report requires -Verdict approve|block"
  }
  $safeTaskId = $TaskId.Trim()

  # Resolve run_id: orchestration manifest first, then scope file
  $resolvedRunId = ""
  $manifestPath = Join-Path $repoRoot ".specbridge/orchestrations/$safeTaskId.orchestration.json"
  if (Test-Path -LiteralPath $manifestPath) {
    try {
      $orch = Get-Content -LiteralPath $manifestPath -Raw -Encoding UTF8 | ConvertFrom-Json
      if ($orch.run_id) { $resolvedRunId = $orch.run_id }
    } catch {}
  }
  if (-not $resolvedRunId) {
    $scopeFile = Join-Path $repoRoot ".specbridge/scopes/$safeTaskId.scope.json"
    if (Test-Path -LiteralPath $scopeFile) {
      try {
        $sc = Get-Content -LiteralPath $scopeFile -Raw -Encoding UTF8 | ConvertFrom-Json
        if ($sc.run_id) { $resolvedRunId = $sc.run_id }
      } catch {}
    }
  }
  if (-not $resolvedRunId) {
    Fail "cannot resolve run_id for task '$safeTaskId' (no orchestration manifest or scope file)"
  }

  # Findings come from repeated -Validation entries: "severity|file|summary"
  $allowedSeverities = @("info", "minor", "major", "blocker")
  $findings = @()
  $findingIndex = 0
  foreach ($entry in $Validation) {
    if ([string]::IsNullOrWhiteSpace($entry)) { continue }
    $parts = $entry.Split("|", 3)
    if ($parts.Count -lt 3) {
      Fail "invalid finding '$entry'. Expected format: severity|file|summary"
    }
    $sev = $parts[0].Trim().ToLowerInvariant()
    if ($allowedSeverities -notcontains $sev) {
      Fail "invalid finding severity '$sev'. Allowed: $($allowedSeverities -join ', ')"
    }
    $findingIndex++
    $findings += [ordered]@{
      id       = "f$findingIndex"
      severity = $sev
      file     = $parts[1].Trim()
      summary  = $parts[2].Trim()
    }
  }

  $blockerCount = @($findings | Where-Object { $_.severity -eq "blocker" }).Count
  if ($blockerCount -gt 0 -and $Verdict -eq "approve") {
    Fail "verdict 'approve' is inconsistent with $blockerCount blocker finding(s); use -Verdict block or downgrade the findings"
  }

  $report = [ordered]@{
    schema_version  = "1"
    task_id         = $safeTaskId
    run_id          = $resolvedRunId
    reviewer        = "agent:reviewer"
    verdict         = $Verdict
    findings        = @($findings)
    reviewed_commit = (Get-GitValue -Arguments @("rev-parse", "--short", "HEAD") -Fallback "unknown")
    summary         = $(if ([string]::IsNullOrWhiteSpace($Summary)) { "review recorded without summary" } else { $Summary })
    created_at      = (Get-Date -Format "o")
  }

  $reviewDir = Join-Path $repoRoot ".specbridge/agent-reviews"
  if (-not (Test-Path $reviewDir)) {
    New-Item -ItemType Directory -Path $reviewDir -Force | Out-Null
  }
  $outRel = ".specbridge/agent-reviews/$safeTaskId.review-agent-report.json"
  $utf8NoBom = New-Object System.Text.UTF8Encoding($false)
  [System.IO.File]::WriteAllText((Join-Path $repoRoot $outRel), ($report | ConvertTo-Json -Depth 5), $utf8NoBom)

  Write-LedgerEntry -TaskId $safeTaskId -Operation "review_report" -Status $Verdict -Detail "findings=$($findings.Count) blockers=$blockerCount" -RunId $resolvedRunId

  Write-CliJson ([ordered]@{
    command  = "specbridge-review-report"
    task_id  = $safeTaskId
    run_id   = $resolvedRunId
    output   = $outRel
    verdict  = $Verdict
    findings = $findings.Count
    blockers = $blockerCount
  })
  exit 0
}

function Invoke-SpecbridgeHandoffCommand {
  if ([string]::IsNullOrWhiteSpace($TaskId)) {
    Fail "specbridge-handoff requires -TaskId"
  }
  if ([string]::IsNullOrWhiteSpace($Agent)) {
    Fail "specbridge-handoff requires -Agent (planner, implementer, reviewer, tester, security, docs, closure)"
  }
  $safeTaskId = $TaskId.Trim()
  $safeAgent = $Agent.Trim().ToLowerInvariant()

  $manifestRel = ".specbridge/orchestrations/$safeTaskId.orchestration.json"
  $manifestPath = Join-Path $repoRoot $manifestRel
  if (-not (Test-Path -LiteralPath $manifestPath)) {
    Fail "no orchestration manifest for task '$safeTaskId'. Run specbridge-orchestrate -TaskId $safeTaskId first."
  }

  $orch = $null
  try { $orch = Get-Content -LiteralPath $manifestPath -Raw -Encoding UTF8 | ConvertFrom-Json } catch {}
  if ($null -eq $orch) {
    Fail "orchestration manifest is not valid JSON: $manifestRel"
  }
  if ($orch.status -eq "completed") {
    Fail "orchestration for '$safeTaskId' is already completed"
  }
  if ($orch.status -eq "cancelled") {
    Fail "orchestration for '$safeTaskId' is cancelled"
  }

  $agents = @($orch.agents)
  $targetIndex = -1
  for ($i = 0; $i -lt $agents.Count; $i++) {
    if ($agents[$i].name -eq $safeAgent) { $targetIndex = $i; break }
  }
  if ($targetIndex -lt 0) {
    $roster = @($agents | ForEach-Object { $_.name }) -join ", "
    Fail "unknown agent '$safeAgent' for task '$safeTaskId'. Roster: $roster"
  }

  $target = $agents[$targetIndex]
  if ($target.status -eq "completed") {
    Fail "agent '$safeAgent' has already handed off for task '$safeTaskId'"
  }
  if ($target.status -eq "skipped") {
    Fail "agent '$safeAgent' was skipped and cannot hand off"
  }
  for ($i = 0; $i -lt $targetIndex; $i++) {
    if ($agents[$i].status -ne "completed" -and $agents[$i].status -ne "skipped") {
      Fail "agent '$($agents[$i].name)' must hand off before '$safeAgent' (handoff protocol is sequential)"
    }
  }

  # Reviewer gate: a reviewer handoff requires a valid review-agent report
  # with verdict approve and no blocker findings.
  $reviewReportRel = $null
  if ($safeAgent -eq "reviewer") {
    $reviewReportRel = ".specbridge/agent-reviews/$safeTaskId.review-agent-report.json"
    $reviewReportPath = Join-Path $repoRoot $reviewReportRel
    if (-not (Test-Path -LiteralPath $reviewReportPath -PathType Leaf)) {
      Fail "reviewer handoff requires a review-agent report. Run: specbridge-review-report -TaskId $safeTaskId -Verdict approve|block first."
    }
    $review = $null
    try { $review = Get-Content -LiteralPath $reviewReportPath -Raw -Encoding UTF8 | ConvertFrom-Json } catch {}
    if ($null -eq $review) {
      Fail "review-agent report is not valid JSON: $reviewReportRel"
    }
    if ($review.task_id -ne $safeTaskId) {
      Fail "review-agent report task_id '$($review.task_id)' does not match '$safeTaskId'"
    }
    if ($review.verdict -ne "approve") {
      Fail "reviewer handoff blocked: review verdict is '$($review.verdict)'"
    }
    $reviewBlockers = @($review.findings | Where-Object { $_.severity -eq "blocker" })
    if ($reviewBlockers.Count -gt 0) {
      Fail "reviewer handoff blocked: report contains $($reviewBlockers.Count) blocker finding(s)"
    }
  }

  $outputRel = $target.output_artifact
  if ([string]::IsNullOrWhiteSpace($outputRel)) {
    $outputRel = ".specbridge/orchestrations/$safeTaskId/$safeAgent-output.json"
  }
  $outputAbs = Join-Path $repoRoot $outputRel
  New-ParentDirectory -Path $outputAbs

  $handoffSummary = if ([string]::IsNullOrWhiteSpace($Summary)) { "handoff recorded without summary" } else { $Summary }
  $artifact = [ordered]@{
    schema_version = "1"
    task_id        = $safeTaskId
    run_id         = $orch.run_id
    agent          = $safeAgent
    review_report  = $reviewReportRel
    role           = $target.role
    status         = "completed"
    summary        = $handoffSummary
    input_artifact = $target.input_artifact
    produced_at    = (Get-Date -Format "o")
  }
  $utf8NoBom = New-Object System.Text.UTF8Encoding($false)
  [System.IO.File]::WriteAllText($outputAbs, ($artifact | ConvertTo-Json -Depth 4), $utf8NoBom)

  $target.status = "completed"
  $nextAgent = $null
  for ($i = $targetIndex + 1; $i -lt $agents.Count; $i++) {
    if ($agents[$i].status -eq "pending") {
      $agents[$i].status = "active"
      $nextAgent = $agents[$i].name
      break
    }
    if ($agents[$i].status -eq "active") {
      $nextAgent = $agents[$i].name
      break
    }
  }

  $remaining = @($agents | Where-Object { $_.status -ne "completed" -and $_.status -ne "skipped" })
  $newStatus = if ($remaining.Count -eq 0) { "completed" } else { "in_progress" }
  $orch.status = $newStatus
  $orch | Add-Member -NotePropertyName "updated_at" -NotePropertyValue (Get-Date -Format "o") -Force
  [System.IO.File]::WriteAllText($manifestPath, ($orch | ConvertTo-Json -Depth 6), $utf8NoBom)

  Write-LedgerEntry -TaskId $safeTaskId -Operation "agent_handoff" -Status "completed" -Detail "agent=$safeAgent next=$(if ($nextAgent) { $nextAgent } else { 'none' })" -RunId $orch.run_id

  Write-CliJson ([ordered]@{
    command              = "specbridge-handoff"
    task_id              = $safeTaskId
    run_id               = $orch.run_id
    agent                = $safeAgent
    output_artifact      = $outputRel
    next_agent           = $nextAgent
    orchestration_status = $newStatus
  })
  exit 0
}

function Invoke-LifecycleGuardCommand {
  $violations = [System.Collections.Generic.List[string]]::new()
  $warnings   = [System.Collections.Generic.List[string]]::new()
  $repoSlug   = ($RepositoryUrl -replace "https://github\.com/", "")

  # Fetch open PRs once
  $previousEap = $ErrorActionPreference; $ErrorActionPreference = "Continue"
  $openPrsRaw = & gh pr list --repo $repoSlug --state open --json number,title,headRefName,baseRefName 2>&1
  $prFetchExit = $LASTEXITCODE
  $ErrorActionPreference = $previousEap

  $openPrs = @()
  if ($prFetchExit -eq 0) {
    try { $openPrs = @($openPrsRaw | ConvertFrom-Json) } catch {}
  }

  $openExecutionPrs   = @($openPrs | Where-Object { $_.headRefName -match "^codex/" })
  $openMemoryClosurePrs = @($openPrs | Where-Object { $_.headRefName -match "^specbridge/memory-closure-" })

  # Check 1: current-goal.json vs open PR state
  $cgPath = Join-Path $repoRoot ".specbridge/state/current-goal.json"
  $currentGoalTaskId = $null
  if (Test-Path $cgPath) {
    try {
      $cg = Get-Content $cgPath -Raw -Encoding UTF8 | ConvertFrom-Json
      $currentGoalTaskId = $cg.current_task_id
      $cgScopePath = Join-Path $repoRoot ".specbridge/scopes/$($cg.current_task_id).scope.json"
      if (Test-Path $cgScopePath) {
        $cgScope = Get-Content $cgScopePath -Raw -Encoding UTF8 | ConvertFrom-Json
        if ($cgScope.status -eq "completed" -and $openExecutionPrs.Count -gt 0) {
          $openPrNums = ($openExecutionPrs | ForEach-Object { "#$($_.number)" }) -join ", "
          $violations.Add("current-goal $($cg.current_task_id) marked completed but execution PR(s) still open: $openPrNums")
        }
      }
    } catch { $warnings.Add("current-goal.json parse error") }
  }

  # Check 2: issue closed but primary execution PR still open
  # Detect by scanning ledger for issue_close success entries
  $ledgerPath = Join-Path $repoRoot ".specbridge/ledger/operations.ndjson"
  $closedTasks = @{}
  if (Test-Path $ledgerPath) {
    foreach ($line in (Get-Content $ledgerPath -Encoding UTF8)) {
      try {
        $entry = $line | ConvertFrom-Json
        if ($null -eq $entry) { continue }
        if ($entry.operation -eq "issue_close" -and $entry.status -match "^(success|already_closed)$") {
          $closedTasks[$entry.task_id] = $true
        }
      } catch {}
    }
  }
  foreach ($closedTask in $closedTasks.Keys) {
    $taskBranches = @($openExecutionPrs | Where-Object { $_.headRefName -match $closedTask })
    if ($taskBranches.Count -gt 0) {
      $prs = ($taskBranches | ForEach-Object { "#$($_.number)" }) -join ", "
      $violations.Add("issue_close recorded for $closedTask but execution PR(s) still open: $prs")
    }
  }

  # Check 3: memory-closure PR exists but primary PR not yet merged
  foreach ($closurePr in $openMemoryClosurePrs) {
    $taskFromBranch = $closurePr.headRefName -replace "^specbridge/memory-closure-", ""
    $primaryPrForTask = @($openExecutionPrs | Where-Object { $_.headRefName -match $taskFromBranch })
    if ($primaryPrForTask.Count -gt 0) {
      $primaryPrNums = ($primaryPrForTask | ForEach-Object { "#$($_.number)" }) -join ", "
      $violations.Add("memory-closure PR #$($closurePr.number) exists for $taskFromBranch but primary PR(s) $primaryPrNums not yet merged")
    }
  }

  # Check 4: blocked path changed without override
  $policyPath = Join-Path $repoRoot ".specbridge/policy.yaml"
  $blockedPaths = @(".env", ".env.*", ".github/workflows/**", "infra/prod/**", "secrets/**")
  $pathOverrides = @()
  if (Test-Path $policyPath) {
    try {
      $policyRaw = Get-Content $policyPath -Raw -Encoding UTF8
      if ($policyRaw -match "path_overrides") {
        # Extract override paths with simple regex
        $overrideMatches = [regex]::Matches($policyRaw, 'path:\s*(.+\.yml)')
        foreach ($m in $overrideMatches) { $pathOverrides += $m.Groups[1].Value.Trim() }
      }
    } catch {}
  }
  $previousEap = $ErrorActionPreference; $ErrorActionPreference = "Continue"
  $changedFiles = & git diff --name-only "origin/$BaseBranch" HEAD 2>&1
  $ErrorActionPreference = $previousEap
  foreach ($f in $changedFiles) {
    if ($f -match "^\.github/workflows/(.+\.yml)$") {
      $wfFile = $f
      $isOverridden = $pathOverrides | Where-Object { $_ -eq ($f -replace "^\.github/workflows/", "") }
      if (-not $isOverridden) {
        $violations.Add("blocked path changed without path_override: $wfFile")
      }
    }
  }

  $guard = if ($violations.Count -gt 0) { "violated" } else { "passed" }

  Write-CliJson ([ordered]@{
    command     = "lifecycle-guard"
    guard       = $guard
    violations  = @($violations)
    warnings    = @($warnings)
    open_execution_prs    = @($openExecutionPrs | ForEach-Object { $_.number })
    open_memory_closure_prs = @($openMemoryClosurePrs | ForEach-Object { $_.number })
    checked_at  = (Get-Date -Format "o")
  })
  if ($violations.Count -gt 0) { exit 1 } else { exit 0 }
}

function Invoke-QuickstartCommand {
  $repoUrl = if (-not [string]::IsNullOrWhiteSpace($RepositoryUrl)) { $RepositoryUrl } else { "https://github.com/<org>/<repo>" }
  $flow = @(
    [ordered]@{
      step    = 1
      command = "specbridge-intake"
      purpose = "Generate governance files (contract, scope, evidence) and push a ready-to-execute branch"
      example = "powershell -ExecutionPolicy Bypass -Command `"& '.\scripts\specbridge.ps1' -Command specbridge-intake -TaskId 'my-feature' -Title 'My feature title' -Goal 'What and why.' -RepositoryUrl '$repoUrl'`""
    }
    [ordered]@{
      step    = 2
      command = "issue-to-merge-github"
      purpose = "Run all 6 GitHub operations autonomously: issue_create, pr_open, ci_wait, merge, issue_close, post_merge_memory"
      example = "powershell -ExecutionPolicy Bypass -Command `"& '.\scripts\specbridge.ps1' -Command issue-to-merge-github -TaskId 'my-feature' -RepositoryUrl '$repoUrl' -Title 'My feature title' -GithubOperation 'issue_create','pr_open','ci_wait','merge','issue_close','post_merge_memory' -MutationMode apply -Force -ConfirmGithubMutation -EvidencePath '.specbridge/github-evidence/my-feature.github-mutation-evidence.json'`""
      note    = "Run from the branch created by specbridge-intake, not from main"
    }
    [ordered]@{
      step    = 3
      command = "specbridge-doctor"
      purpose = "Verify system health: no active scopes with violations, no premature closures"
      example = "powershell -ExecutionPolicy Bypass -Command `"& '.\scripts\specbridge.ps1' -Command specbridge-doctor`""
    }
    [ordered]@{
      step    = 4
      command = "generate-dashboard"
      purpose = "Regenerate the HTML status dashboard with current scope, ledger, and goal state"
      example = "powershell -ExecutionPolicy Bypass -Command `"& '.\scripts\specbridge.ps1' -Command generate-dashboard`""
    }
  )

  Write-CliJson ([ordered]@{
    command              = "quickstart"
    ok                   = $true
    description          = "SpecBridge shortest safe path: intake to dashboard"
    recommended_flow     = $flow
    next_command_example = $flow[0].example
    notes                = @(
      "Step 2 must run from the branch created by specbridge-intake (not main)"
      "All governance gates are pre-set to true by specbridge-intake"
      "CI must pass before merge; lifecycle-guard enforces ordering"
      "doctor and generate-dashboard can run at any time"
    )
  })
}

