param(
  [string] $ReportPath = ".specbridge/generated-review-reports/generated-pr-review.review-report.json",
  [string] $OutputPath = ".specbridge/generated-review-reports/generated-pr-review-comment.md"
)

$ErrorActionPreference = "Stop"

Write-Output "SpecBridge PR review comment rendering started."

if (-not (Test-Path $ReportPath)) {
  Write-Output "FAIL missing PR review report: $ReportPath"
  exit 1
}

$report = Get-Content $ReportPath -Raw | ConvertFrom-Json

New-Item -ItemType Directory -Force -Path (Split-Path -Parent $OutputPath) | Out-Null

$findings = @($report.findings)
$blockingFindings = @($findings | Where-Object { $_.blocking -eq $true })
$totalFindings = $findings.Count

$lines = New-Object System.Collections.Generic.List[string]

$lines.Add("<!-- specbridge-pr-review-report -->")
$lines.Add("## SpecBridge PR Review Report")
$lines.Add("")
$lines.Add("| Field | Value |")
$lines.Add("|---|---|")
$lines.Add("| Reviewer | ``$($report.reviewer)`` |")
$lines.Add("| Result | ``$($report.result)`` |")
$lines.Add("| Findings | ``$totalFindings`` |")
$lines.Add("| Blocking findings | ``$($blockingFindings.Count)`` |")
$lines.Add("")
$lines.Add("### Summary")
$lines.Add("")
$lines.Add($report.summary)
$lines.Add("")

if ($totalFindings -gt 0) {
  $lines.Add("### Findings")
  $lines.Add("")

  foreach ($finding in $findings) {
    $blockingText = if ($finding.blocking) { "yes" } else { "no" }
    $lineText = if ($null -eq $finding.line) { "n/a" } else { "$($finding.line)" }

    $lines.Add("- **Severity:** ``$($finding.severity)``")
    $lines.Add("  - **Category:** ``$($finding.category)``")
    $lines.Add("  - **File:** ``$($finding.file)``")
    $lines.Add("  - **Line:** ``$lineText``")
    $lines.Add("  - **Blocking:** ``$blockingText``")
    $lines.Add("  - **Evidence:** $($finding.evidence)")
    $lines.Add("  - **Recommendation:** $($finding.recommendation)")
    $lines.Add("")
  }
} else {
  $lines.Add("No findings reported.")
  $lines.Add("")
}

$lines.Add("---")
$lines.Add("Generated by SpecBridge deterministic review reporting. No live Claude, Codex, MCP, deployment automation, or user secrets were used.")

$lines | Set-Content -Path $OutputPath -Encoding UTF8

Write-Output "Rendered PR review comment: $OutputPath"
Write-Output "SpecBridge PR review comment rendering passed."
exit 0
